import type { Category } from "@/lib/quotes";

/**
 * 16x16 pixel sprites. Palette keys:
 *   k outline  a accent  d accent shade  w white  s skin  y gold  g steel  e eye
 *   . transparent
 */
export const SPRITES: Record<Category | "scroll", string[]> = {
  wisdom: [
    ".......kk.......",
    "......kaak......",
    ".....kaayak.....",
    ".....kaaaak.....",
    "....kaadaaak....",
    "....kaaaaadk....",
    "..kkkkkkkkkkkk..",
    "..kddddddddddk..",
    "...kssssssssk...",
    "...kskesskesk...",
    "...kssssssssk...",
    "...kwwwsswwwk...",
    "..kawwwwwwwwak..",
    ".kaaawwwwwwaaak.",
    ".kaaaawwwwaaaak.",
    "..kkkkkkkkkkkk..",
  ],
  code: [
    ".......kk.......",
    ".......ky.......",
    "...kkkkkkkkkk...",
    "..kaaaaaaaaaak..",
    "..kakkkkkkkkak..",
    "..kakekkkkekak..",
    "kkkakkkkkkkkakkk",
    "kgkaaaaaaaaaakgk",
    "kgkakwkwkwkwakgk",
    "kkkaaaaaaaaaakkk",
    "...kkkkkkkkkk...",
    "....kgggggggk...",
    "..kkddddddddkk..",
    "..kdaykaaykaadk.",
    "..kddddddddddk..",
    "...kkk....kkk...",
  ],
  gaming: [
    "................",
    "....k......k....",
    ".....k....k.....",
    "....kaaaaaak....",
    "...kaaaaaaaak...",
    "..kaakkaakkaak..",
    "..kaakeaakeaak..",
    ".kaaaaaaaaaaaak.",
    ".kakaaaaaaaakak.",
    ".kakaaaaaaaakak.",
    ".kakkaaaaaakkak.",
    ".kk.kakkkkak.kk.",
    "....kk....kk....",
    "................",
    "................",
    "................",
  ],
  science: [
    "......kkkk......",
    "......kwwk......",
    "......kwwk......",
    "......kwwk......",
    ".....kwwwwk.....",
    ".....kwwwwk.....",
    "....kwwwwwwk....",
    "....kaaaaaak....",
    "...kaawaaaaak...",
    "...kaaaaawaak...",
    "..kaaaaaaaaaak..",
    "..kaaawaaaaaak..",
    ".kddaaaaaaawddk.",
    ".kddddddddddddk.",
    "..kkkkkkkkkkkk..",
    "................",
  ],
  grit: [
    ".....kkkkkk.....",
    "....kggggggk....",
    "...kgwggggggk...",
    "...kgggggggggk..",
    "..kgggaaaagggk..",
    "..kggkkkkkkggk..",
    "..kgkekkkkekgk..",
    "..kggkkkkkkggk..",
    "..kgggggggggk...",
    "...kgkgkgkgk....",
    "....kgggggk.....",
    "..kkkkkkkkkkk...",
    ".kaaaaaaaaaaak..",
    ".kayaaaaaaaayak.",
    "..kkkkkkkkkkkk..",
    "................",
  ],
  scroll: [
    "................",
    "..kkkkkkkkkkkk..",
    ".kyyyyyyyyyyyyk.",
    "..kwwwwwwwwwwk..",
    "..kwkkkkkkkwwk..",
    "..kwwwwwwwwwwk..",
    "..kwkkkkkkwwwk..",
    "..kwwwwwwwwwwk..",
    "..kwkkkkkkkkwk..",
    "..kwwwwwwwwwwk..",
    "..kwkkkkkwwwwk..",
    "..kwwwwwwwwwwk..",
    ".kyyyyyyyyyyyyk.",
    "..kkkkkkkkkkkk..",
    "................",
    "................",
  ],
};
